apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.fullname }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  selector:
    matchLabels:
      {{- with .Values.deployment.selectorLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.deployment.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.deployment.fullname }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.service.containerPortName }}
              containerPort: {{ .Values.service.containerPort }}
              protocol:  {{ .Values.service.protocol }}
          livenessProbe:
            periodSeconds: {{ .Values.deployment.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.liveness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.deployment.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.deployment.liveness.failureThreshold }}
            successThreshold: {{ .Values.deployment.liveness.successThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.service.containerPortName }}
          readinessProbe:
            periodSeconds: {{ .Values.service.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.service.readiness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.service.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.service.readiness.failureThreshold }}
            successThreshold: {{ .Values.service.readiness.successThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.service.containerPortName }}
